### ISSUE TITLE
未设置loadingView

### ISSUE THREAD

**Issue by ydl00** [xiong-it/LoadingLayout#1]
第137 行
  try {
            mLoadingView = LayoutInflater.from(context).inflate(loadingViewLayoutId, null);
            mEmptyView = LayoutInflater.from(context).inflate(emptyViewLayoutId, null);
            mErrorView = LayoutInflater.from(context).inflate(errorViewLayoutId, null);
            mLoadingAnim = AnimatorInflater.loadAnimator(context, loadingAnimId);
        } catch (Exception e) {
            e.printStackTrace();
        }
当 未设置 布局 loadingView 属性时, 设置的 其他 mEmptyView  mErrorView  mLoadingAnim  无效
希望能够更加完善

**Comment by xiong-it** [comment]
v1.0.2已修复，感谢！
